### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by wwylele** [wwylele/KEYTranslationProject#1]
### 需要修改的ROM文件
- [x] `/env/Common/GameFont1.gfa`
- [x] `/env/Common/GameFont2.gfa`
- [x] ~~`/env/Common/GameFontResult.gfa`~~
- [x] `/message/*/DemoMessage_EnvDemo.bin`
- [x] ~~`/message/*/DemoMessage_StaffCredits.bin`~~
- [x] `/message/*/DemoMessage_StoryDemo.bin`
- [x] `/message/*/FlfMessage_Game.bin`
- [x] `/message/*/FlfMessage_System.bin`
- [x] `/message/*/ItemMessage_Character.bin`
- [x] `/message/*/ItemMessage_Demo.bin`
- [x] `/message/*/ItemMessage_Interior.bin`
- [x] `/message/*/ItemMessage_KeyItem.bin`
- [x] `/message/*/ItemMessage_Operation.bin`
- [x] `/message/*/ItemMessage_Pattern.bin`
- [x] ~~`/message/*/ItemMessage_Room.bin`~~
- [x] `/message/*/ItemMessage_Sound.bin`
- [x] `/message/*/ItemMessage_StageName.bin`
- [ ] `/chara/env/PGW/*_US.gfa`
### 需要的工具
- [x] GFA文件读写器
- [x] ~~bin~~GFMC文本文件读写器
- [x] brfnt修改器

**Comment by duangsuse** [comment]
←_←那三个工具在哪下..
分享到度云里了？
还是自己找
（刚才没看REDAME,,所以问了）
